import { TemplateDefinition, TemplateSchema } from "../types";
import { DESIGN_TOKENS } from "../tokens";

export const orbitTemplate: TemplateDefinition = TemplateSchema.parse({
  id: "orbit",
  name: "Celestial Orbit",
  description:
    "An astronomical aerospace theme featuring a central celestial sphere, concentric orbit rings, satellite nodes, and cosmic particle starfields.",
  category: "Aerospace & Science",
  templateVersion: "1.0.0",
  bestFor: "Aerospace Engineers, Roboticists, Physics Researchers, Backend Architects & Deep Tech Founders",
  targetAudience: ["Scientific Directors", "Enterprise Recruiters", "Aerospace Leads"],

  supportedSections: ["hero", "about", "experience", "projects", "skills", "education", "contact"],
  supportedObjects: [
    "sphere",
    "torus",
    "NeonRings",
    "SphereOrb",
    "model",
    "particles",
  ],
  supportedAnimations: ["orbit", "rotate", "float"],

  defaultTheme: {
    id: "theme-orbit-celestial",
    name: "Celestial Orbit",
    variant: "dark",
    colors: {
      primary: DESIGN_TOKENS.colors.orbitBlue,
      secondary: DESIGN_TOKENS.colors.deepIndigo,
      accent: "#38BDF8",
      background: "#02040A",
      surface: "#080E1E",
      textPrimary: "#F8FAFC",
      textMuted: "#7DD3FC",
      border: "rgba(56, 189, 248, 0.22)",
      glowColor: DESIGN_TOKENS.shadows.glowBlue,
    },
    typography: {
      fontFamily: "Inter",
      headingFontFamily: "Outfit",
      baseSize: "md",
      scaleRatio: 1.25,
    },
    glassmorphism: {
      enabled: true,
      blurIntensity: 16,
      opacity: 0.65,
      borderWidth: 1,
      reflectionGlow: true,
    },
    animations: {
      reducedMotion: false,
      transitionSpeed: "normal",
      entranceEffects: true,
      hoverSpring: true,
    },
    layout: {
      containerWidth: "wide",
      cardStyle: "glass",
      borderRadius: "lg",
    },
  },

  defaultScene: {
    id: "scene-orbit-default",
    name: "Celestial Orbit System",
    version: "1.0.0",
    camera: {
      type: "perspective",
      fov: 46,
      position: [0, 1.2, 8.5],
      target: [0, 0, 0],
      near: 0.1,
      far: 1000,
      zoom: 1,
      controls: {
        enabled: true,
        autoRotate: true,
        autoRotateSpeed: 0.4,
        enableZoom: false,
        enablePan: false,
        maxPolarAngle: Math.PI / 2 + 0.15,
        minPolarAngle: Math.PI / 3,
        dampingFactor: 0.05,
      },
    },
    lighting: {
      preset: "deep-space",
      ambientIntensity: 0.3,
      lights: [
        { id: "star-sun", type: "directional", color: "#BAE6FD", intensity: 3.5, position: [5, 4, 4] },
        { id: "nebula-glow", type: "point", color: "#818CF8", intensity: 2.5, position: [-4, -2, -3] },
      ],
    },
    environment: {
      preset: "night",
      background: { type: "solid", color: "#02040A" },
      blur: 0.85,
      fog: { enabled: true, color: "#02040A", near: 6, far: 24 },
      stars: { enabled: true, count: 1800, color: "#FFFFFF", radius: 60, depth: 50, speed: 0.3 },
    },
    postProcessing: {
      bloom: { enabled: true, intensity: 1.25, luminanceThreshold: 0.2, luminanceSmoothing: 0.9 },
      chromaticAberration: { enabled: false, offset: [0.002, 0.002] },
      vignette: { enabled: true, darkness: 0.6, offset: 0.35 },
    },
    performance: {
      tier: "medium",
      maxPixelRatio: 2,
      shadows: false,
      postprocessing: true,
      maxParticles: 2000,
      maxLights: 4,
      maxObjects: 25,
      reducedMotion: false,
    },
    nodes: [
      {
        id: "orbit-planet-core",
        componentType: "SphereOrb",
        position: [0, 0, 0],
        rotation: [0.2, 0, 0],
        scale: [1.3, 1.3, 1.3],
        materialProps: { color: "#38BDF8", metalness: 0.85, roughness: 0.2, emissive: "#0369A1", emissiveIntensity: 0.4 },
        animation: { type: "rotate", rotateSpeed: [0.02, 0.2, 0], speed: 0.3 },
        interactive: { hoverScale: 1.06, hoverGlow: true, pointerParallax: true, parallaxStrength: 0.35 },
        visible: true,
      },
      {
        id: "orbit-rings-equatorial",
        componentType: "NeonRings",
        position: [0, 0, 0],
        rotation: [Math.PI / 3.5, 0, 0.3],
        scale: [1.8, 1.8, 1.8],
        materialProps: { color: "#818CF8", opacity: 0.85, transparent: true, emissive: "#818CF8", emissiveIntensity: 0.7 },
        animation: { type: "rotate", rotateSpeed: [0, 0.1, 0.05], speed: 0.2 },
        interactive: { pointerParallax: true, parallaxStrength: 0.2 },
        visible: true,
      },
      {
        id: "orbit-satellite-probe",
        componentType: "box",
        position: [2.6, 0.8, 0],
        rotation: [0.4, 0.5, 0.2],
        scale: [0.25, 0.25, 0.25],
        materialProps: { color: "#FFFFFF", metalness: 0.9, roughness: 0.1, emissive: "#BAE6FD", emissiveIntensity: 0.5 },
        animation: { type: "orbit", speed: 0.6, rotateSpeed: [0.2, 0.3, 0] },
        interactive: { hoverScale: 1.2, hoverGlow: true },
        visible: true,
      },
    ],
    quality: "high",
    interactivity: { mouseParallax: true, parallaxFactor: 0.45, scrollDriven: true },
  },

  defaultLayout: {
    containerWidth: "wide",
    heroLayout: "split-canvas-right",
    cardStyle: "glass",
    navStyle: "floating-pill",
    sectionSpacing: "normal",
  },

  defaultMotion: {
    scrollDriven: true,
    mouseParallax: true,
    parallaxStrength: 0.45,
    rotationSpeed: 0.4,
    transitionPreset: "smooth-fade",
  },

  performanceProfile: "Medium Complexity (Orbital Dynamics)",
  performance: {
    tier: "medium",
    recommendedParticles: 1500,
    maxLights: 3,
    maxDpr: 2,
    supportsPostProcessing: true,
    supportsShadows: false,
  },

  previewImage: "/templates/orbit-preview.webp",
});
