import { TemplateDefinition, TemplateSchema } from "../types";
import { DESIGN_TOKENS } from "../tokens";

export const neuralTemplate: TemplateDefinition = TemplateSchema.parse({
  id: "neural",
  name: "Neural Nexus",
  description:
    "An AI & Machine Learning engineered dimension with synaptic node clusters, particle vortexes, and high-contrast technical typography.",
  category: "Technology",
  templateVersion: "1.0.0",
  bestFor: "AI/ML Engineers, Data Scientists, Systems Architects & Full-Stack Developers",
  targetAudience: ["Tech Recruiters", "Founders", "Engineering Managers"],

  supportedSections: ["hero", "about", "experience", "projects", "skills", "education", "contact"],
  supportedObjects: [
    "NeuralNodes",
    "ParticleVortex",
    "CyberGrid",
    "FloatingMeshNode",
    "model",
    "particles",
  ],
  supportedAnimations: ["float", "pulse", "rotate", "orbit"],

  defaultTheme: {
    id: "theme-neural-nexus",
    name: "Neural Tech",
    variant: "dark",
    colors: {
      primary: DESIGN_TOKENS.colors.cyberCyan,
      secondary: DESIGN_TOKENS.colors.cyberPurple,
      accent: DESIGN_TOKENS.colors.neonEmerald,
      background: "#040711",
      surface: "#0A0F20",
      textPrimary: "#FFFFFF",
      textMuted: "#8899B0",
      border: "rgba(0, 240, 255, 0.18)",
      glowColor: DESIGN_TOKENS.shadows.glowCyan,
    },
    typography: {
      fontFamily: "Space Grotesk",
      headingFontFamily: "Space Grotesk",
      baseSize: "md",
      scaleRatio: 1.25,
    },
    glassmorphism: {
      enabled: true,
      blurIntensity: 18,
      opacity: 0.72,
      borderWidth: 1,
      reflectionGlow: true,
    },
    animations: {
      reducedMotion: false,
      transitionSpeed: "normal",
      entranceEffects: true,
      hoverSpring: true,
    },
    layout: {
      containerWidth: "wide",
      cardStyle: "glass",
      borderRadius: "md",
    },
  },

  defaultScene: {
    id: "scene-neural-default",
    name: "Synaptic Neural Matrix",
    version: "1.0.0",
    camera: {
      type: "perspective",
      fov: 48,
      position: [0, 0, 7.5],
      target: [0, 0, 0],
      near: 0.1,
      far: 1000,
      zoom: 1,
      controls: {
        enabled: true,
        autoRotate: true,
        autoRotateSpeed: 0.5,
        enableZoom: false,
        enablePan: false,
        maxPolarAngle: Math.PI / 2 + 0.1,
        minPolarAngle: Math.PI / 3,
        dampingFactor: 0.05,
      },
    },
    lighting: {
      preset: "cyberpunk",
      ambientIntensity: 0.35,
      lights: [
        { id: "light-cyan", type: "point", color: "#00F0FF", intensity: 4, position: [3, 3, 3] },
        { id: "light-emerald", type: "point", color: "#00FF66", intensity: 3, position: [-3, -2, -2] },
      ],
    },
    environment: {
      preset: "night",
      background: { type: "solid", color: "#040711" },
      blur: 0.8,
      fog: { enabled: true, color: "#040711", near: 4, far: 20 },
      stars: { enabled: true, count: 1200, color: "#00F0FF", radius: 50, depth: 40, speed: 0.4 },
    },
    postProcessing: {
      bloom: { enabled: true, intensity: 1.1, luminanceThreshold: 0.25, luminanceSmoothing: 0.85 },
      chromaticAberration: { enabled: false, offset: [0.001, 0.001] },
      vignette: { enabled: true, darkness: 0.5, offset: 0.3 },
    },
    performance: {
      tier: "high",
      maxPixelRatio: 2,
      shadows: false,
      postprocessing: true,
      maxParticles: 2500,
      maxLights: 4,
      maxObjects: 30,
      reducedMotion: false,
    },
    nodes: [
      {
        id: "neural-network-nodes",
        componentType: "NeuralNodes",
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1.2, 1.2, 1.2],
        materialProps: { color: "#00F0FF", metalness: 0.8, roughness: 0.2, emissive: "#00F0FF", emissiveIntensity: 0.6 },
        animation: { type: "rotate", rotateSpeed: [0.05, 0.15, 0], speed: 0.4 },
        interactive: { hoverScale: 1.08, hoverGlow: true, pointerParallax: true, parallaxStrength: 0.3 },
        visible: true,
      },
      {
        id: "neural-particle-vortex",
        componentType: "ParticleVortex",
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1.5, 1.5, 1.5],
        materialProps: { color: "#00FF66", opacity: 0.75, transparent: true },
        animation: { type: "rotate", speed: 0.4 },
        interactive: { pointerParallax: true, parallaxStrength: 0.2 },
        visible: true,
      },
      {
        id: "neural-cyber-grid",
        componentType: "CyberGrid",
        position: [0, -2.2, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        materialProps: { color: "#00F0FF", opacity: 0.15, transparent: true },
        animation: { type: "none" },
        interactive: {},
        visible: true,
      },
    ],
    quality: "high",
    interactivity: { mouseParallax: true, parallaxFactor: 0.4, scrollDriven: true },
  },

  defaultLayout: {
    containerWidth: "wide",
    heroLayout: "split-canvas-right",
    cardStyle: "glass",
    navStyle: "floating-pill",
    sectionSpacing: "normal",
  },

  defaultMotion: {
    scrollDriven: true,
    mouseParallax: true,
    parallaxStrength: 0.4,
    rotationSpeed: 0.5,
    transitionPreset: "smooth-fade",
  },

  performanceProfile: "High Quality WebGL (Recruiter Friendly)",
  performance: {
    tier: "high",
    recommendedParticles: 2000,
    maxLights: 4,
    maxDpr: 2,
    supportsPostProcessing: true,
    supportsShadows: false,
  },

  previewImage: "/templates/neural-preview.webp",
});
