import { SceneConfig, SceneSchema } from "../schemas/scene.schema";

export const ORBIT_SCENE_TEMPLATE: SceneConfig = SceneSchema.parse({
  id: "template-orbit-01",
  name: "Orbit Exoplanet",
  version: "1.0.0",
  camera: {
    type: "perspective",
    fov: 45,
    position: [0, 0, 8],
    target: [0, 0, 0],
    near: 0.1,
    far: 1000,
    controls: {
      enabled: true,
      autoRotate: true,
      autoRotateSpeed: 0.8,
      enableZoom: false,
      enablePan: false,
      dampingFactor: 0.05,
    },
  },
  lighting: {
    preset: "deep-space",
    ambientIntensity: 0.4,
    lights: [
      { id: "orbit-light-1", type: "point", color: "#00F0FF", intensity: 4, position: [4, 4, 3], distance: 25 },
      { id: "orbit-light-2", type: "point", color: "#9D00FF", intensity: 3, position: [-4, -3, -2], distance: 25 },
      { id: "orbit-light-3", type: "directional", color: "#ffffff", intensity: 1.5, position: [0, 6, 4] },
    ],
  },
  environment: {
    preset: "night",
    background: { type: "solid", color: "#030712" },
    blur: 0.8,
    fog: { enabled: true, color: "#030712", near: 5, far: 25 },
    stars: { enabled: true, count: 1800, color: "#ffffff", radius: 60, depth: 40, speed: 0.6 },
  },
  postProcessing: {
    bloom: { enabled: true, intensity: 1.2, luminanceThreshold: 0.2, luminanceSmoothing: 0.9 },
    chromaticAberration: { enabled: false, offset: [0.002, 0.002] },
    vignette: { enabled: true, darkness: 0.6, offset: 0.3 },
  },
  nodes: [
    {
      id: "orbit-planet-core",
      componentType: "SphereOrb",
      position: [0, 0, 0],
      rotation: [0.2, 0, 0],
      scale: [1.6, 1.6, 1.6],
      materialProps: {
        type: "standard",
        color: "#00F0FF",
        emissive: "#0077B6",
        emissiveIntensity: 0.4,
        roughness: 0.2,
        metalness: 0.8,
        wireframe: false,
        transparent: true,
        opacity: 0.95,
      },
      animation: {
        type: "rotate",
        axis: "y",
        speed: 0.4,
        rotateSpeed: [0.05, 0.2, 0],
        floatAmplitude: 0.15,
        floatSpeed: 0.8,
      },
      interactive: {
        hoverScale: 1.08,
        hoverGlow: true,
        pointerParallax: true,
        parallaxStrength: 0.3,
      },
      visible: true,
    },
    {
      id: "orbit-ring-outer",
      componentType: "NeonRings",
      position: [0, 0, 0],
      rotation: [0.4, 0.2, 0],
      scale: [1.8, 1.8, 1.8],
      materialProps: {
        type: "basic",
        color: "#9D00FF",
        emissive: "#9D00FF",
        transparent: true,
        opacity: 0.85,
      },
      animation: {
        type: "rotate",
        axis: "all",
        speed: 0.3,
        rotateSpeed: [0.1, 0.15, 0.05],
        floatAmplitude: 0,
      },
      interactive: {
        hoverScale: 1.05,
        hoverGlow: true,
        pointerParallax: true,
      },
      visible: true,
    },
  ],
  quality: "high",
});
