import { AssetManifestEntry } from "./types";

export const APPROVED_ASSET_MANIFEST: Record<string, AssetManifestEntry> = {
  "planet-01": {
    id: "planet-01",
    name: "Cybernetic Exoplanet",
    type: "model",
    category: "space",
    file: "/assets/3d/planet-01.glb",
    preview: "/assets/previews/planet-01.webp",
    polyBudget: 12000,
    fileSize: 450000,
    allowed: true,
    tags: ["space", "astronomy", "aerospace", "planet", "orbit"],
    optimization: { draco: true, meshopt: false, ktx2: false, lodLevels: 2 },
  },
  "orbit-ring-01": {
    id: "orbit-ring-01",
    name: "Planetary Orbit Rings",
    type: "model",
    category: "space",
    file: "/assets/3d/orbit-ring-01.glb",
    preview: "/assets/previews/orbit-ring-01.webp",
    polyBudget: 8500,
    fileSize: 280000,
    allowed: true,
    tags: ["space", "orbit", "rings", "saturn", "gravity"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "satellite-01": {
    id: "satellite-01",
    name: "Orbital Sensor Probe",
    type: "model",
    category: "technology",
    file: "/assets/3d/satellite-01.glb",
    preview: "/assets/previews/satellite-01.webp",
    polyBudget: 15000,
    fileSize: 620000,
    allowed: true,
    tags: ["technology", "space", "telecom", "aerospace", "probe"],
    optimization: { draco: true, meshopt: true, ktx2: false, lodLevels: 2 },
  },
  "neural-core-01": {
    id: "neural-core-01",
    name: "Synaptic Neural Cluster",
    type: "model",
    category: "technology",
    file: "/assets/3d/neural-core-01.glb",
    preview: "/assets/previews/neural-core-01.webp",
    polyBudget: 18000,
    fileSize: 740000,
    allowed: true,
    tags: ["ai", "machine-learning", "neural", "synapse", "brain", "network"],
    optimization: { draco: true, meshopt: true, ktx2: false, lodLevels: 2 },
  },
  "server-tower-01": {
    id: "server-tower-01",
    name: "Quantum Compute Node",
    type: "model",
    category: "devices",
    file: "/assets/3d/server-tower-01.glb",
    preview: "/assets/previews/server-tower-01.webp",
    polyBudget: 11000,
    fileSize: 490000,
    allowed: true,
    tags: ["hardware", "compute", "cloud", "datacenter", "devices"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "glass-slab-01": {
    id: "glass-slab-01",
    name: "Translucent Refraction Slab",
    type: "model",
    category: "abstract",
    file: "/assets/3d/glass-slab-01.glb",
    preview: "/assets/previews/glass-slab-01.webp",
    polyBudget: 4200,
    fileSize: 180000,
    allowed: true,
    tags: ["glass", "prism", "refraction", "translucent", "modern"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "crystal-cluster-01": {
    id: "crystal-cluster-01",
    name: "Prismatic Beryl Crystal",
    type: "model",
    category: "geometric",
    file: "/assets/3d/crystal-cluster-01.glb",
    preview: "/assets/previews/crystal-cluster-01.webp",
    polyBudget: 7800,
    fileSize: 310000,
    allowed: true,
    tags: ["crystal", "mineral", "geometric", "polyhedron", "gem"],
    optimization: { draco: true, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "torus-gyro-01": {
    id: "torus-gyro-01",
    name: "Kinetic Gyroscopic Monolith",
    type: "model",
    category: "creative",
    file: "/assets/3d/torus-gyro-01.glb",
    preview: "/assets/previews/torus-gyro-01.webp",
    polyBudget: 16000,
    fileSize: 680000,
    allowed: true,
    tags: ["kinetic", "sculpture", "art", "creative", "rotation"],
    optimization: { draco: true, meshopt: true, ktx2: false, lodLevels: 2 },
  },
  "arch-column-01": {
    id: "arch-column-01",
    name: "Parametric Ionic Pillar",
    type: "model",
    category: "architecture",
    file: "/assets/3d/arch-column-01.glb",
    preview: "/assets/previews/arch-column-01.webp",
    polyBudget: 9500,
    fileSize: 410000,
    allowed: true,
    tags: ["architecture", "spatial", "column", "parametric", "classical"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "minimal-sphere-01": {
    id: "minimal-sphere-01",
    name: "Refined Matte Orb",
    type: "model",
    category: "geometric",
    file: "/assets/3d/minimal-sphere-01.glb",
    preview: "/assets/previews/minimal-sphere-01.webp",
    polyBudget: 3200,
    fileSize: 120000,
    allowed: true,
    tags: ["minimal", "clean", "simple", "sphere", "matte"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "diploma-scroll-01": {
    id: "diploma-scroll-01",
    name: "Academic Ribbon Scroll",
    type: "model",
    category: "education",
    file: "/assets/3d/diploma-scroll-01.glb",
    preview: "/assets/previews/diploma-scroll-01.webp",
    polyBudget: 5400,
    fileSize: 220000,
    allowed: true,
    tags: ["education", "degree", "academic", "university", "student"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "briefcase-icon-01": {
    id: "briefcase-icon-01",
    name: "Executive Portfolio Monogram",
    type: "model",
    category: "professional",
    file: "/assets/3d/briefcase-icon-01.glb",
    preview: "/assets/previews/briefcase-icon-01.webp",
    polyBudget: 6200,
    fileSize: 260000,
    allowed: true,
    tags: ["professional", "career", "enterprise", "executive"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
  "leaf-foliage-01": {
    id: "leaf-foliage-01",
    name: "Bioluminescent Sprout",
    type: "model",
    category: "nature",
    file: "/assets/3d/leaf-foliage-01.glb",
    preview: "/assets/previews/leaf-foliage-01.webp",
    polyBudget: 6900,
    fileSize: 290000,
    allowed: true,
    tags: ["nature", "organic", "plant", "growth", "sustainability"],
    optimization: { draco: false, meshopt: false, ktx2: false, lodLevels: 1 },
  },
};

export function getManifestAsset(id: string): AssetManifestEntry | null {
  return APPROVED_ASSET_MANIFEST[id] || null;
}

export function getAllManifestAssets(): AssetManifestEntry[] {
  return Object.values(APPROVED_ASSET_MANIFEST);
}

export function getAssetsByCategory(category: string): AssetManifestEntry[] {
  return Object.values(APPROVED_ASSET_MANIFEST).filter((a) => a.category === category);
}
